### ISSUE TITLE
Improve integration of fraction-matcher screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-equality#2]
1. Adding the sim dependency wasn't enough. I had to add its preloads/phetlibs. That should not be necessary?
2. I'm having to allow overriding of the screen's name (since we want it different here).

**Comment by samreid** [comment]
Our build and development setup doesn't currently support transitive dependencies.

**Comment by jonathanolson** [comment]
This was cleaned up, closing.
