### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fractions-equality#4]
As pointed out in https://github.com/phetsims/QA/issues/267, this sim needs screenshots for 1.0.

**Comment by amanda-phet** [comment]
@phet-steele the main screenshot should be the equality lab screen.

**Comment by phet-steele** [comment]
Commited. Main followed by alts:

![fractions-equality-screenshot](https://user-images.githubusercontent.com/5863899/51767109-a281a000-2099-11e9-8c83-86c9b0c1efab.png)

![fractions-equality-screenshot-alt1](https://user-images.githubusercontent.com/5863899/51767112-a57c9080-2099-11e9-939b-f04a9e47ac5f.png)

![fractions-equality-screenshot-alt2](https://user-images.githubusercontent.com/5863899/51767113-a57c9080-2099-11e9-9ccd-97aa931d0710.png)

![fractions-equality-screenshot-alt3](https://user-images.githubusercontent.com/5863899/51767114-a57c9080-2099-11e9-90ba-6fcd84c0a1fd.png)

**Comment by phet-steele** [comment]
> For the Game, I wonder if we should show the smiley face like in Fraction Matcher? @phet-steele any reason for not doing that here?

To be different than Fraction Matcher; to show the state before answering. Do you want it there?


> I don't think we need to show the blue/pink container view.

Removed.

**Comment by amanda-phet** [comment]
Nope that all sounds good. Thanks!
